<a href="https://colab.research.google.com/github/Hannah1123/UTS_ML2019_ID13135684/blob/master/A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Review on 'Gradient-Based Learning Applied to Document Recognition'

#Introduction

#Content 


Rumelhart and Hinton[1] firstly came up with the algorithm of back propagation in 1985 which made the training of neural networks feasible. A few years later, LeCun[2] applied back propagation to realize the recognition of handwritten zip code. At the same time, though convolutional neural networks had not be named yet, they were firstly implemented.   
This paper is focus on handwritten character recognition using a new classifier called LeNet-5. This reaserch has implemented real-life document recognition system which consist of multiple modules including feature extraction, segmentation, recognition and language modeling.  
One of the major challenge in handwritting recognition is to extract the separate characters from a word or a sentence. It is difficult and extremely costly to creat a labeled database which consist of incorrectly segmented characters. Convolutional Neural Networks are described in this paper which were designed to learn to seperate out features directly from pixel images. The implement of convolutional neural network is helpful for emliminating the need for hand-crafted feature extrators. The results of this network has been shown the advantages in training a system at word or sentence level. At the same time, the use of convolutional neural networks significantly save the computational cost.  
Convolutional neural networks combine local receptive field, shared weights and sub-sampling.One of the typical convolutional network is LeNet-5 which is presented below.  
![LeNet-5](https://github.com/Hannah1123/UTS_ML2019_ID13135684/blob/master/1566745651(1).png)   
As for the recognition, this research compares several methods for isolated handwritten digit recognition including Linear Classifier, Pairwise Linear Classifier, Baseline Nearest Neighbor Classifier, PCA, One-hidden Layer Fully Connected Multilayer Neural Network, Two-hidden Layer Fully Connected Multilayer Neural Network, LeNet-1, LeNet-4, Boosted LeNet-4,TDC, SVM.  
This research also presents the elimination of segmentation heuristics by using Apace-Displacement Neural Network approach. Heuristic Over-Segmentation is used to generate a lot of hypothese in parallel in order to postpone desisions.


#Innovation 


The background at the time of the work is that Hubel and Wiesel shows that by connecting an electrode to a neuron, they can listen to the response of the neuron to a bar of light. They came up with a new understanding of how V1 cerebral cortical neurons work.[3] In 1980, Kunihiko Fukishima proposed a neural network model for mechanism of visual pattern recognition called neocognitron.[4]
Rumelhart and Hinton firstly came up with the algorithm of back propagation in 1985 which made the training of neural networks feasible. A few years later, LeCun applied back propagation to realize the recognition of handwritten zip code. At the same time, though convolutional neural networks had not be named yet, they were firstly implemented.   
The creative idea is a new architecture of convolutional neural networks. LeNet-5 consist of 7 layers: three Convolutions(C1, C3, C5), two Subsampling(S2, S4), one Full connection(F6) and a Gaussian connections(Output layer).
The convolutions are comprises of filters which involve trainable parameters(weights). 
The Subsampling is to reduce the spatial size of the outcome from convolutions to reduce computation to quarter in the network. At the sanme time, the process of subsampling has the feature of invariance including translation invariance, rotation invariance and scale invariance.  
The methods adopting neural network has been shown to have better performance. They not only run much faster but also require much less space.  
This research successfully applied Grandient-Based Learning to Convolutional Neural Networks which has been shown to learn appropriate features from examples. As a result, Grandient-Based Learning has been proved that it is useful for learning in large system. 

# Technical quality
rate如何评价论文中工作的技术质量(要考虑已完成的工作)。200字  
定义了CNN的基本结构
CNN 的鼻祖
提出新的架构 using。。。


The technical development if of high quality. this research compares several methods for isolated handwritten digit recognition including Linear Classifier, Pairwise Linear Classifier, Baseline Nearest Neighbor Classifier, PCA, One-hidden Layer Fully Connected Multilayer Neural Network, Two-hidden Layer Fully Connected Multilayer Neural Network, LeNet-1, LeNet-4, Boosted LeNet-4,TDC, SVM. The authors supported their theory using ...

# Application and X-factor
该技术是否符合其应用域，还可以用于什么application domain？给一些该research发展的建议。该文章的内容能否在课堂上激起讨论的火花？有什么interest 发现 在该文章中？200字  
图像识别 语音识别 人脸识别
梯度消失
复杂问题处理不理想
计算跟不上

I find the proposal in the paper promising. ...

# Presentation
该文章的presentation的质量如何？rate：how easy it was to follow the argument in the paper; presentation风格; depth of the argument; and clarity of
the presentation.#100字  


The overall strucutre is clear. I found reading is easy / difficult. The paper could have been more attractive if the authors had organised ... / provided ...

# References


# Draft and Experiment Area

First impression

What is my chosen paper to read?  
 **Gradient-Based Learning Applied to Document
Recognition**  

What type of the main contribution the paper has made? 
A theory or proposition (revealing something, from unknown to known)
A method or algorithm (inventing a technique, from undoable to doable)
Before reading the main body of the paper, write down your first impression obtained from its abstract and short introduction.  
**basic of CNN**   

Why does the paper attract you, such as, How it surprised you? Why do you think it addresses an important topic that will be helpful in your future study of machine learning?  
**CNN is one of the basic of machine learning**

Read the paper abstract and introduction, list here all the notions that you don't know the precise meaning. If you think you have completed your list, compare the list with people around you who have chosen the same or a similar paper.  
 


*   **multilayer nueral networks**
*   **backpropagation algorithm**

*   **gradient-based learning**
*   **language modeling**

*   **consvolutional neural networks**
*   **feature extraction**

*   **LeNet-5**
*   **loss function**





(During the next 7 days) Re-consider the central problem of the paper.

In [15]:
#卷积：tf.nn.conv2d

import tensorflow as tf

input = tf.Variable(tf.random_normal([1, 3, 3, 5]))
filter = tf.Variable(tf.random_normal([1, 1, 5, 2]))
op = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='VALID')
sess = tf.InteractiveSession()
tf.global_variables_initializer().run()
print(sess.run(op))

[[[[ 1.8813169  -1.5202918 ]
   [ 2.2968774   0.0779307 ]
   [-0.5835189   0.07772313]]

  [[ 0.43748137  2.6572256 ]
   [-0.45102707  2.6266615 ]
   [-0.6183824   1.7114183 ]]

  [[ 3.8748915   0.7497179 ]
   [ 0.8550094   0.01759055]
   [ 0.3192418  -0.01004475]]]]


/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1735: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [12]:
#池化tf.nn.max_pool

import tensorflow as tf

a = tf.constant([
    [[1.0, 2.0, 3.0, 4.0],
     [5.0, 6.0, 7.0, 8.0],
     [8.0, 7.0, 6.0, 5.0],
     [4.0, 3.0, 2.0, 1.0]],
    [[4.0, 3.0, 2.0, 1.0],
     [8.0, 7.0, 6.0, 5.0],
     [1.0, 2.0, 3.0, 4.0],
     [5.0, 6.0, 7.0, 8.0]]
])

a = tf.reshape(a, [1, 4, 4, 2])

pooling = tf.nn.max_pool(a, ksize=[1, 2, 2, 1], strides=[1, 1, 1, 1], padding='VALID')
with tf.Session() as sess:
    image = sess.run(a)
    print(image)
    result = sess.run(pooling)
    print(result)

[[[[1. 2.]
   [3. 4.]
   [5. 6.]
   [7. 8.]]

  [[8. 7.]
   [6. 5.]
   [4. 3.]
   [2. 1.]]

  [[4. 3.]
   [2. 1.]
   [8. 7.]
   [6. 5.]]

  [[1. 2.]
   [3. 4.]
   [5. 6.]
   [7. 8.]]]]
[[[[8. 7.]
   [6. 6.]
   [7. 8.]]

  [[8. 7.]
   [8. 7.]
   [8. 7.]]

  [[4. 4.]
   [8. 7.]
   [8. 8.]]]]


In [26]:
import tensorflow as tf  
from tensorflow.examples.tutorials.mnist import input_data
  
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)  
  
sess = tf.InteractiveSession()  
  
# 训练数据
x = tf.placeholder("float", shape=[None, 784])  
# 训练标签数据
y_ = tf.placeholder("float", shape=[None, 10])  
# 把x更改为4维张量
x_image0 = tf.reshape(x, [-1, 28, 28, 1])

#28*28->32*32
x_image = tf.pad(x_image0,[[0,0],[2,2],[2,2],[0,0]])

def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape=shape)
    return tf.Variable(initial)
  
#卷积
def conv2d(x,W):
  return tf.nn.conv2d(x,W,strides=[1,1,1,1],padding='VALID')  

#池化
def max_pool_2x2(x):
  return tf.nn.max_pool(x,ksize=[1,2,2,1],strides=[1,2,2,1],padding='VALID')


def lenet5_layer(layer,weight,bias):
  w_conv=weight_variable(weight)
  b_conv=bias_variable(bias)
  h_conv=conv2d(layer,w_conv)+b_conv
  return max_pool_2x2(h_conv)

#卷积C1+池化S2:->6*28*28 ->6*14*14
layer1=lenet5_layer(x_image,[5,5,1,6],[6])

#卷积C3+池化S4： ->16*10*10 ->16*5*5
layer2=lenet5_layer(layer1,[5,5,6,16],[16])

#卷积C5：-> 120*1*1
w_conv3=weight_variable([5,5,16,120])
b_conv3=bias_variable([120])

layer3=conv2d(layer2,w_conv3)+b_conv3
layer3=tf.reshape(layer3,[-1,120])
"""

W_conv1 = weight_variable([5, 5, 1, 6])
b_conv1 = bias_variable([6])
h_conv1=conv2d(x_image,W_conv1)+b_conv1
h_pool1 = max_pool_2x2(h_conv1)
"""

#F6: 
def dense_layer(layer,weight,bias):
  w_fc=weight_variable(weight)
  b_fc=bias_variable(bias)
  return tf.matmul(layer,w_fc)+b_fc

con_layer1=dense_layer(layer3,[120,84],[84])

#output
con_layer2=dense_layer(con_layer1,[84,10],[10])
keep_prob = tf.placeholder(tf.float32) 
y_conv=tf.nn.softmax(tf.nn.dropout(con_layer2,keep_prob))#减少过拟合

  
  
#定义交叉熵损失函数  
cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y_conv), reduction_indices=[1]))  
  
#选择优化器，并让优化器最小化损失函数/收敛, 反向传播  
train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)  
  
# tf.argmax()返回的是某一维度上其数据最大所在的索引值，在这里即代表预测值和真实值  
# 判断预测值y和真实值y_中最大数的索引是否一致，y的值为1-10概率  
correct_prediction = tf.equal(tf.argmax(y_conv,1), tf.argmax(y_,1))  
  
# 用平均值来统计测试准确率  
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))  
  
#开始训练  
sess.run(tf.global_variables_initializer())  
for i in range(1000):  
    batch = mnist.train.next_batch(100)  
    if i%100 == 0:  
        train_accuracy = accuracy.eval(feed_dict={x:batch[0], y_: batch[1], keep_prob: 1.0}) #评估阶段不使用Dropout  
        print("step %d, training accuracy %g" % (i, train_accuracy))  
    train_step.run(feed_dict={x: batch[0], y_: batch[1], keep_prob: 0.5}) #训练阶段使用50%的Dropout  
  
  
#在测试数据上测试准确率  
print("test accuracy %g" % accuracy.eval(feed_dict={x: mnist.test.images, y_: mnist.test.labels, keep_prob: 1.0}))

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1735: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


step 0, training accuracy 0.14
step 100, training accuracy 0.61
step 200, training accuracy 0.78
step 300, training accuracy 0.85
step 400, training accuracy 0.85
step 500, training accuracy 0.85
step 600, training accuracy 0.89
step 700, training accuracy 0.86
step 800, training accuracy 0.93
step 900, training accuracy 0.96
test accuracy 0.9299
